### PR TITLE
PageExtension - getCartScript

### PR DESCRIPTION
**Pull request by jsirish**
adds getCartScript() to Page, makes $CartScript in template available to all pages in site.

### CODE REVIEW

**Comment by muskie9** [comment]
Just food for thought, do we want to make the slide out an optional store setting? We can merge this in once the tests are done and update it later if we want to.

**Comment by jsirish** [comment]
I think we could, but since it's just setting a getter variable, and not actually a requirement, it's already optional. They would have to use the $CartScript variable in the top level Page template for it to work. Simplest solution and all that.

$CartScript probably needs to be referenced in the ReadMe as well, if it's not already.

**Comment by muskie9** [comment]
That's right, forgot it needs to get included in the template. Do we remove it from `ProductPage.ss` then in the module? If someone uses simple and just runs off the module layouts will calling it twice error?

**Comment by korthjp17** [comment]
I think it does cause an error if it gets included twice

**Comment by jsirish** [comment]
I'm not getting any errors locally, but I think moving it from ProductPage.ss template is smart.

Should probably remove getCartScript() from ProductPage.php as well?

**Comment by muskie9** [comment]
Probably for consistency, I think it would end up using the `ProductPage.php` function in the end so that wouldn't cause issues, but having both would make us maintain it in two places. So I'm good with removing it from product.

**Pull request merged**
