### PR TITLE
BUGFIX unavailable product still shows add to cart

### PR DESCRIPTION
**Pull request by muskie9**
I'm open to discussion on how best to adjust this, but wanted to get something rolling as it's critical to get this fixed.

### CODE REVIEW

**Comment by muskie9** [comment]
This should be handled by parts of the js in #223. We'll be adjusting that PR to handle this bug as it was originally intended to do it.

**Comment by muskie9** [comment]
This is re-opened as our 1.0 ux disabled the whole form if the overall product was marked as not available. Changing the ux would go agains master (1.2)

**Comment by jsirish** [comment]
looks like this has to be rebased and force pushed. i'll wait to test

**Comment by muskie9** [comment]
Should be set for testing.

**Pull request merged**
