### PR TITLE
Update add to cart form to be built in SS

### LINKED ISSUE #40: Use SilverStripe to generate add to cart form

### PR DESCRIPTION
**Pull request by muskie9**
fixes #40

This is an initial PR. I don't expect it to work 100% right away, but it's a pretty good start. Once we're confident it's working as it should then we'll merge.

This also updates Float to Decimal which is more widely accepted across different databases.

### CODE REVIEW

**Comment by muskie9** [comment]
@jsirish my guess is we'll need this tested in a test store setup in FoxyCart to ensure everything is working properly.

**Comment by muskie9** [comment]
I've refactored the js and I think it's working properly now, but needs testing.

**Comment by muskie9** [comment]
Seems there's still something a bit off when I tried to add a product to cart. Might be missing a field, I'll go back through and double check.

**Comment by jsirish** [comment]
I'll pull this down to test sometime today. If you need a big store catalog, you could grab shop.dynamicdoes.com's DB

**Pull request merged**
