### PR TITLE
BUGFIX jquery error if no product options

### PR DESCRIPTION
**Pull request by muskie9**
Only include product option jquery if product options exist on the product.

### CODE REVIEW

**Comment by jsirish** [comment]
sanity check looks good, should be safe to merge

**Comment by muskie9** [comment]
It seems that SS doesn't have anything to add classes to the `<option>` items within the dropdown fields. This will prevent us from adding the `outOfStock` class to the option elements that should disable the Add To Cart button.

**Comment by muskie9** [comment]
The PR is updated to keep the UX the same as it was originally setup. Out of stock options are selectable and disable the add to cart button.

**Comment by jsirish** [comment]
tested, looks good

**Pull request merged**
