### PR TITLE
OptionItem, ProductImage Summary Fields

### PR DESCRIPTION
**Pull request by jsirish**
Option Item - added Available as a summary field

ProductImage - added CMSThumbnail as summary field

### CODE REVIEW

**Comment by muskie9** [comment]
I'll double check the failure on this. It may be how I have the test written as it's the PGSQL database instance.

**Comment by jsirish** [comment]
Just realized I published this to dynamic/foxystripe, not my account. Once we merge this I'll zap the remote branch on dynamic

**Comment by jsirish** [comment]
hold off on a merge for now, found another bug or two that I'll wrap up in here

**Comment by muskie9** [comment]
Looks good, merging.

**Comment by muskie9** [comment]
Just realized we'll need to specify a minimum requirement for GridFieldBulkEditingTool as the new function is for newer versions of that module.

**Pull request merged**
